"""Utilities for generating professional PDF and Markdown security reports."""

import os
from datetime import datetime
from typing import List, Dict
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.units import inch

from axiom.models.findings import AgentState, Finding, Severity


class ReportGenerator:
    """Base class for report generation."""

    def __init__(self, state: AgentState):
        self.state = state
        self.target = state.target
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def _get_all_findings(self) -> List[Finding]:
        """Consolidate findings from all agents."""
        all_findings = []
        if self.state.analysis:
            all_findings.extend(self.state.analysis.findings)
        if self.state.web_analysis:
            all_findings.extend(self.state.web_analysis.findings)
        if self.state.exploit_analysis:
            all_findings.extend(self.state.exploit_analysis.potential_exploits)
        return all_findings


class MarkdownGenerator(ReportGenerator):
    """Generates clean Markdown reports."""

    def generate(self) -> str:
        """Create a full markdown report."""
        lines = []
        lines.append(f"# Axiom Security Assessment Report")
        lines.append(f"**Target:** {self.target}")
        lines.append(f"**Date:** {self.timestamp}")
        lines.append("\n---\n")

        if self.state.report_analysis:
            lines.append("## 1. Executive Summary")
            lines.append(self.state.report_analysis.executive_summary)
            lines.append("\n")
            lines.append("## 2. Key Findings Summary")
            lines.append(self.state.report_analysis.key_findings_summary)
            lines.append("\n")

        lines.append("## 3. Detailed Security Findings")
        findings = self._get_all_findings()
        if not findings:
            lines.append("No critical security findings were identified during this assessment.")
        else:
            for f in findings:
                lines.append(f"### {f.title} ({f.severity.value.upper()})")
                lines.append(f"- **Category:** {f.category}")
                if f.port: lines.append(f"- **Port:** {f.port}")
                if f.service: lines.append(f"- **Service:** {f.service}")
                lines.append(f"\n**Description:**\n{f.description}")
                lines.append(f"\n**Evidence:**\n```\n{f.evidence}\n```")
                lines.append(f"\n**Remediation:**\n{f.remediation}")
                if f.cve_ids: lines.append(f"\n**CVEs:** {', '.join(f.cve_ids)}")
                lines.append("\n---")

        if self.state.report_analysis:
            lines.append("## 4. Remediation Roadmap")
            for i, step in enumerate(self.state.report_analysis.remediation_roadmap):
                lines.append(f"{i+1}. {step}")

        lines.append("\n\n---\n*Disclaimer: This report is for authorized use only. Generated by Axiom AI Security Pentest Suite.*")
        return "\n".join(lines)


class PDFGenerator(ReportGenerator):
    """Generates professional branded PDF reports using ReportLab."""

    def generate(self, output_path: str):
        """Create a professional PDF report."""
        doc = SimpleDocTemplate(output_path, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        # Custom Styles
        title_style = ParagraphStyle(
            'TitleStyle', parent=styles['Heading1'],
            fontSize=24, spaceAfter=20, textColor=colors.HexColor("#e63946")
        )
        h2_style = ParagraphStyle(
            'H2Style', parent=styles['Heading2'],
            fontSize=18, spaceBefore=15, spaceAfter=10, textColor=colors.HexColor("#1d3557")
        )
        
        # Cover Page
        story.append(Paragraph("Axiom Security Assessment", title_style))
        story.append(Spacer(1, 0.5 * inch))
        story.append(Paragraph(f"<b>Target:</b> {self.target}", styles['Normal']))
        story.append(Paragraph(f"<b>Date:</b> {self.timestamp}", styles['Normal']))
        story.append(Paragraph("<b>Classification:</b> CONFIDENTIAL / INTERNAL USE", styles['Normal']))
        story.append(PageBreak())

        # Executive Summary
        if self.state.report_analysis:
            story.append(Paragraph("1. Executive Summary", h2_style))
            story.append(Paragraph(self.state.report_analysis.executive_summary, styles['Normal']))
            story.append(Spacer(1, 0.2 * inch))

        # Findings Table
        story.append(Paragraph("2. Findings Overview", h2_style))
        findings = self._get_all_findings()
        
        data = [["Finding", "Severity", "Category"]]
        for f in findings:
            data.append([f.title[:40] + "..." if len(f.title) > 40 else f.title, 
                         f.severity.value.upper(), 
                         f.category])

        if len(data) > 1:
            table = Table(data, colWidths=[3.5*inch, 1*inch, 1.5*inch])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#457b9d")),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            story.append(table)
        else:
            story.append(Paragraph("No critical findings identified.", styles['Normal']))
            
        story.append(PageBreak())

        # Detailed Findings
        story.append(Paragraph("3. Detailed Security Findings", h2_style))
        for f in findings:
            story.append(Paragraph(f"<b>{f.title}</b>", styles['Heading3']))
            story.append(Paragraph(f"<b>Severity:</b> {f.severity.value.upper()} | <b>Category:</b> {f.category}", styles['Normal']))
            story.append(Spacer(1, 0.1 * inch))
            story.append(Paragraph(f"<b>Description:</b> {f.description}", styles['Normal']))
            story.append(Spacer(1, 0.1 * inch))
            story.append(Paragraph(f"<b>Remediation:</b> {f.remediation}", styles['Normal']))
            story.append(Spacer(1, 0.2 * inch))
            story.append(Paragraph("-" * 80, styles['Normal']))

        doc.build(story)
